# secret 
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
data:
  username: dXNlcm5hbWU= # base64 for 'username'
  password: cGFzc3dvcmQ= # base64 for 'password'

# a pod that prints the secret values 
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod
spec:
  containers:
  - name: secret-test-container
    image: busybox
    command: ["/bin/sh", "-c", "echo Username: $(cat /etc/secret/username); echo Password: $(cat /etc/secret/password); sleep 3600"]
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/secret
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: my-secret

# To create the secret and pod, use:
# kubectl apply -f test.yml
# To view the pod logs and see the secret values, use:
# kubectl logs secret-test-pod