# a docker compose for a wordpress container with myswl
services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - vol_wordpress:/var/www/html
    networks:
      - mynetwork
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork
    restart: always
networks:
  mynetwork:
    driver: bridge
volumes:
  vol_wordpress:
    driver: local
  db_data:
    driver: local