apiVersion: apps/v1
kind: DaemonSet
metadata:
 name: ejemplo-daemonset
spec:
 selector:
   matchLabels:
     app: mi-aplicacion
 template:
   metadata:
     labels:
       app: mi-aplicacion
   spec:
     containers:
     - name: contenedor-de-ejemplo
       image: imagen-de-ejemplo:latest
       ports:
       - containerPort: 80