# an ubuntu image that does an exho of an environment variable
FROM ubuntu:25.04
LABEL maintainer="Rojaldo" email="algo@loquesea.com"
LABEL version="1.0"
LABEL description="A Dockerfile for a basic Ubuntu image that prints an environment variable."
ENV MY_ENV="Hello, World!"

# echo a message 
ENTRYPOINT ["/bin/echo"]